Allow self-referential BelongsTo relations
tokio-rs/toasty pull request #55
Opened 2024-12-31 15:01 UTC by TannerRogalsky

The BelongsTo has no indirection so for self-referential relations fails to compile due to an infinitely sized struct. This checks if the model and the relation share the same target and, for BelongsTo relations, adds a Box to the property type.

2024-12-31 15:02 UTC, TannerRogalsky commented on src/core/src/schema/verify.rs
> +                    }
I wasn't really sure what this assert is protecting against so gated it behind the same check. There's likely a better solution.

2025-01-14 22:12 UTC, carllerche requested changes
Hi! Thanks for submitting the PR. Sorry for the review delay. I was on vacation.

I agree that supporting self-referential belongs to is needed. I have a few requests before this gets merged.

First, instead of an example, could you add a test in the `tests/client` directory?

For the implementation strategy, I left an inline note, but I am wondering if having `value` in `BelongsTo<T>` always be boxed would be a better idea. It would simplify the code gen (avoiding having to conditionally box the field) and the structure sizes would be smaller.

what do you think?

2025-01-14 22:12 UTC, carllerche commented on src/codegen/src/model/body.rs
> +                            #name: Box<BelongsTo<#ty>>,
Interesting, it might be worth always allocating in `BelongsTo`, especially since the structs might be big and not always loaded.

2025-01-14 22:12 UTC, carllerche commented on src/core/src/schema/verify.rs
> +                    }
Is this assert being hit? `pair` should never be equal to `FieldId::placeholder()` once the schema is built. If the assert is being hit there is probably a bug.

2025-01-18 13:22 UTC, TannerRogalsky commented
I think this library is a little too early days for me to use even as an experiment. Best of luck!

2025-01-18 13:22 UTC, closed without merging